version: 0.2

env:
  variables:
    ENVIRONMENT: "staging"

phases:
  pre_build:
    commands:
      - echo "=== Iniciando build para STAGING ==="
      - echo Fazendo login no ECR...      
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 804826263064.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=804826263064.dkr.ecr.us-east-1.amazonaws.com/bia
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Gerando imagem da BIA para STAGING...
      - docker build -t $REPOSITORY_URI:latest --build-arg ENVIRONMENT=staging .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  
  post_build:
    commands:
      - echo Build finalizado com sucesso em `date`
      - echo Fazendo push da imagem para o ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Gerando artefato da imagem para o ECS
      - printf '[{"name":"bia-staging","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "=== Deploy para STAGING concluído ==="

artifacts:
  files: imagedefinitions.json
