version: 0.2

phases:
  pre_build:
    commands:
      - echo "Build para Elastic Beanstalk iniciado..."
      - npm install --loglevel=error
  build:
    commands:
      - echo "Build da aplicação para EB..."
      - cd client && npm install --include=dev --legacy-peer-deps --loglevel=error
      - cd client && VITE_API_URL=/api npm run build
      - cd ..
  post_build:
    commands:
      - echo "Preparando artefatos para Elastic Beanstalk..."
      - zip -r bia-app.zip . -x "node_modules/*" "client/node_modules/*" ".git/*"

artifacts:
  files:
    - bia-app.zip
  name: bia-eb-artifact
